version: '3'

services:
  app:
    build: .
    container_name: loopback-test-app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: loopback-test-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - loopback-test-dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=loopback_test
      - MYSQL_ROOT_PASSWORD=root

volumes:
  loopback-test-dbdata:
    external: true
